// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as OrcaJs from "../OrcaJs.bs.js";
import * as Context from "../Context.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

var make = React.forwardRef(function (param, imperativeRef) {
      var onReady = param.onReady;
      var onChange = param.onChange;
      var elementsState = React.useContext(Context.elementsContext);
      var sessionState = React.useContext(Context.paymentMethodsSessionContext);
      var createdRef = React.useRef(false);
      var match = React.useState(function () {
            return Context.defaultCardFormContext;
          });
      var setCardFormValue = match[1];
      var cardFormValue = match[0];
      React.useEffect((function () {
              if (!createdRef.current) {
                if (sessionState.isPresent) {
                  Core__Option.forEach(sessionState.session, (function (session) {
                          var group = session.createCardForm();
                          createdRef.current = true;
                          setCardFormValue(function (param) {
                                return {
                                        createField: group.create,
                                        confirmPayment: (function () {
                                            return Promise.resolve(OrcaJs.unsupportedOnSurfaceError("confirmPayment", "vault", "tokenize"));
                                          }),
                                        tokenize: group.tokenize,
                                        on: group.on,
                                        update: group.update,
                                        deinit: group.deinit,
                                        getFields: (function () {
                                            return group.fields.contents;
                                          }),
                                        isReady: true
                                      };
                              });
                        }));
                } else if (elementsState.isReady) {
                  var group = elementsState.createCardForm();
                  createdRef.current = true;
                  setCardFormValue(function (param) {
                        return {
                                createField: group.create,
                                confirmPayment: group.confirmPayment,
                                tokenize: (function () {
                                    return Promise.resolve(OrcaJs.unsupportedOnSurfaceError("tokenize", "payments", "confirmPayment"));
                                  }),
                                on: group.on,
                                update: group.update,
                                deinit: group.deinit,
                                getFields: (function () {
                                    return group.fields.contents;
                                  }),
                                isReady: true
                              };
                      });
                }
                
              }
              
            }), [
            elementsState,
            sessionState
          ]);
      React.useEffect(function () {
            if (cardFormValue.isReady) {
              Core__Option.forEach(onChange, (function (cb) {
                      cardFormValue.on("change", cb);
                    }));
              Core__Option.forEach(onReady, (function (cb) {
                      cardFormValue.on("ready", cb);
                    }));
            }
            
          });
      React.useImperativeHandle(imperativeRef, (function () {
              return {
                      confirmPayment: cardFormValue.confirmPayment,
                      tokenize: cardFormValue.tokenize,
                      update: cardFormValue.update,
                      deinit: cardFormValue.deinit,
                      on: cardFormValue.on,
                      getFields: cardFormValue.getFields
                    };
            }), [cardFormValue]);
      return JsxRuntime.jsx(Context.CardFormContextProvider.make, {
                  value: cardFormValue,
                  children: param.children
                });
    });

export {
  make ,
}
/* make Not a pure module */
