// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function CardFieldWrapper(props) {
  var __imperativeRef = props.imperativeRef;
  var onBlur = props.onBlur;
  var onFocus = props.onFocus;
  var onReady = props.onReady;
  var onChange = props.onChange;
  var fieldType = props.fieldType;
  var imperativeRef = __imperativeRef !== undefined ? Caml_option.valFromOption(__imperativeRef) : null;
  var cardFormCtx = React.useContext(Context.cardFormContext);
  var divRef = React.useRef(null);
  var handleRef = React.useRef(undefined);
  var didMountRef = React.useRef(false);
  var resolvedId = Core__Option.getOr(props.id, fieldType);
  var containerId = "hyper-card-field-" + resolvedId;
  var resolvedOptions = Core__Option.getOr(props.options, {});
  var serializedOptions = JSON.stringify(resolvedOptions);
  var bindCallbacks = function (handle) {
    Core__Option.forEach(onChange, (function (cb) {
            handle.on("change", cb);
          }));
    Core__Option.forEach(onReady, (function (cb) {
            handle.on("ready", cb);
          }));
    Core__Option.forEach(onFocus, (function (cb) {
            handle.on("focus", cb);
          }));
    Core__Option.forEach(onBlur, (function (cb) {
            handle.on("blur", cb);
          }));
  };
  React.useEffect((function () {
          if (!cardFormCtx.isReady) {
            return ;
          }
          var existingHandle = handleRef.current;
          var handle;
          if (existingHandle !== undefined) {
            handle = existingHandle;
          } else {
            var createdHandle = cardFormCtx.createField(fieldType, resolvedOptions);
            handleRef.current = createdHandle;
            handle = createdHandle;
          }
          bindCallbacks(handle);
          handle.mount("#" + containerId);
          return (function () {
                    handle.unmount();
                  });
        }), [
        cardFormCtx.isReady,
        containerId
      ]);
  React.useEffect(function () {
        Core__Option.forEach(handleRef.current, bindCallbacks);
      });
  React.useEffect((function () {
          if (didMountRef.current) {
            Core__Option.forEach(handleRef.current, (function (handle) {
                    handle.update(resolvedOptions);
                  }));
          } else {
            didMountRef.current = true;
          }
        }), [serializedOptions]);
  React.useImperativeHandle(imperativeRef, (function () {
          return {
                  mount: (function (selector) {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.mount(selector);
                            }));
                    }),
                  unmount: (function () {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.unmount();
                            }));
                    }),
                  destroy: (function () {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.destroy();
                            }));
                    }),
                  update: (function (updatedOptions) {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.update(updatedOptions);
                            }));
                    }),
                  focus: (function () {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.focus();
                            }));
                    }),
                  blur: (function () {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.blur();
                            }));
                    }),
                  clear: (function () {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.clear();
                            }));
                    }),
                  on: (function (eventName, cb) {
                      Core__Option.forEach(handleRef.current, (function (handle) {
                              handle.on(eventName, cb);
                            }));
                    })
                };
        }), []);
  return JsxRuntime.jsx("div", {
              ref: Caml_option.some(divRef),
              id: containerId
            });
}

var make = CardFieldWrapper;

export {
  make ,
}
/* react Not a pure module */
