// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as CardFieldWrapper from "./CardFieldWrapper.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

var make = React.forwardRef(function (param, imperativeRef) {
      return JsxRuntime.jsx(CardFieldWrapper.make, {
                  fieldType: "cardExpiry",
                  id: param.id,
                  options: param.options,
                  onChange: param.onChange,
                  onReady: param.onReady,
                  onFocus: param.onFocus,
                  onBlur: param.onBlur,
                  imperativeRef: Caml_option.some(imperativeRef)
                });
    });

export {
  make ,
}
/* make Not a pure module */
