// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.bs.js";
import * as React from "react";
import * as Context from "../Context.bs.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Elements(props) {
  var options = props.options;
  var stripe = props.stripe;
  var match = React.useState(function () {
        return Context.defaultSwitchContext;
      });
  var setSwitchState = match[1];
  var match$1 = React.useState(function () {
        return Context.defaultElementsContext;
      });
  var setElementsState = match$1[1];
  React.useEffect((function () {
          Core__Promise.$$catch(Promise.all([
                      stripe,
                      Utils.normalizeToPromise(options)
                    ]).then(function (param) {
                    var resolvedOptions = param[1];
                    var switchInstance = param[0];
                    var elementOptions = Context.elementsOptionObjMapper(resolvedOptions);
                    var orcaElementsConfig = switchInstance.elements(resolvedOptions);
                    var newElemValues_update = orcaElementsConfig.update;
                    var newElemValues_getElement = orcaElementsConfig.getElement;
                    var newElemValues_fetchUpdates = orcaElementsConfig.fetchUpdates;
                    var newElemValues_create = orcaElementsConfig.create;
                    var newElemValues_updateIntent = orcaElementsConfig.updateIntent;
                    var newElemValues_createCardForm = orcaElementsConfig.createCardForm;
                    var newElemValues = {
                      options: elementOptions,
                      update: newElemValues_update,
                      getElement: newElemValues_getElement,
                      fetchUpdates: newElemValues_fetchUpdates,
                      create: newElemValues_create,
                      updateIntent: newElemValues_updateIntent,
                      createCardForm: newElemValues_createCardForm,
                      isReady: true
                    };
                    var switchValClone_clientSecret = elementOptions.clientSecret;
                    var switchValClone_confirmPayment = switchInstance.confirmPayment;
                    var switchValClone_confirmCardPayment = switchInstance.confirmCardPayment;
                    var switchValClone_retrievePaymentIntent = switchInstance.retrievePaymentIntent;
                    var switchValClone_paymentRequest = switchInstance.paymentRequest;
                    var switchValClone_initPaymentSession = switchInstance.initPaymentSession;
                    var switchValClone_completeUpdateIntent = switchInstance.completeUpdateIntent;
                    var switchValClone_initiateUpdateIntent = switchInstance.initiateUpdateIntent;
                    var switchValClone_confirmTokenization = switchInstance.confirmTokenization;
                    var switchValClone = {
                      clientSecret: switchValClone_clientSecret,
                      confirmPayment: switchValClone_confirmPayment,
                      confirmCardPayment: switchValClone_confirmCardPayment,
                      retrievePaymentIntent: switchValClone_retrievePaymentIntent,
                      paymentRequest: switchValClone_paymentRequest,
                      initPaymentSession: switchValClone_initPaymentSession,
                      completeUpdateIntent: switchValClone_completeUpdateIntent,
                      initiateUpdateIntent: switchValClone_initiateUpdateIntent,
                      confirmTokenization: switchValClone_confirmTokenization
                    };
                    setSwitchState(function (param) {
                          return switchValClone;
                        });
                    setElementsState(function (param) {
                          return newElemValues;
                        });
                    return Promise.resolve(switchValClone);
                  }), (function (err) {
                  console.error("[Elements] Failed to initialise hyper promise:", err);
                  return Promise.resolve(Context.defaultSwitchContext);
                }));
        }), [
        stripe,
        options
      ]);
  return JsxRuntime.jsx(Context.SwitchContextProvider.make, {
              value: match[0],
              children: JsxRuntime.jsx(Context.ElementsContextProvider.make, {
                    value: match$1[0],
                    children: props.children
                  })
            });
}

var make = Elements;

export {
  make ,
}
/* react Not a pure module */
