// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Utils from "../Utils.bs.js";
import * as React from "react";
import * as Context from "../Context.bs.js";
import * as Core__Promise from "@rescript/core/src/Core__Promise.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function HyperPaymentMethodsSession(props) {
  var options = props.options;
  var hyper = props.hyper;
  var match = React.useState(function () {
        return Context.pendingPaymentMethodsSessionContext;
      });
  var setSessionState = match[1];
  React.useEffect((function () {
          Core__Promise.$$catch(Promise.all([
                      hyper,
                      Utils.normalizeToPromise(options)
                    ]).then(function (param) {
                    var session = param[0].paymentMethodsSession(param[1]);
                    var newSessionValues_session = session;
                    var newSessionValues = {
                      session: newSessionValues_session,
                      isPresent: true
                    };
                    setSessionState(function (param) {
                          return newSessionValues;
                        });
                    return Promise.resolve(newSessionValues);
                  }), (function (err) {
                  console.error("[HyperPaymentMethodsSession] Failed to initialise hyper promise:", err);
                  return Promise.resolve(Context.pendingPaymentMethodsSessionContext);
                }));
        }), [
        hyper,
        options
      ]);
  return JsxRuntime.jsx(Context.PaymentMethodsSessionContextProvider.make, {
              value: match[0],
              children: props.children
            });
}

var make = HyperPaymentMethodsSession;

export {
  make ,
}
/* react Not a pure module */
