// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";
import * as Js_promise from "rescript/lib/es6/js_promise.js";
import * as JsxRuntime from "react/jsx-runtime";

function HyperManagementElements(props) {
  var options = props.options;
  var hyper = props.hyper;
  var paymentMethodsManagementElementOptions = Context.paymentMethodsManagementElementsOptionObjMapper(options);
  var match = React.useState(function () {
        return Context.defaultPaymentMethodsManagementSwitchContext;
      });
  var setSwitchState = match[1];
  var match$1 = React.useState(function () {
        return Context.defaultPaymentMethodsManagementElementsContext;
      });
  var setElementsState = match$1[1];
  React.useEffect((function () {
          ((function (__x) {
                  return Js_promise.then_((function (switchInstance) {
                                var orcaElementsConfig = switchInstance.paymentMethodsManagementElements(options);
                                var newElemValues_update = orcaElementsConfig.update;
                                var newElemValues_getElement = orcaElementsConfig.getElement;
                                var newElemValues_fetchUpdates = orcaElementsConfig.fetchUpdates;
                                var newElemValues_create = orcaElementsConfig.create;
                                var newElemValues = {
                                  options: paymentMethodsManagementElementOptions,
                                  update: newElemValues_update,
                                  getElement: newElemValues_getElement,
                                  fetchUpdates: newElemValues_fetchUpdates,
                                  create: newElemValues_create
                                };
                                var switchValClone_ephemeralKey = paymentMethodsManagementElementOptions.ephemeralKey;
                                var switchValClone_paymentRequest = switchInstance.paymentRequest;
                                var switchValClone = {
                                  ephemeralKey: switchValClone_ephemeralKey,
                                  paymentRequest: switchValClone_paymentRequest
                                };
                                setSwitchState(function (param) {
                                      return switchValClone;
                                    });
                                setElementsState(function (param) {
                                      return newElemValues;
                                    });
                                return Promise.resolve(switchValClone);
                              }), __x);
                })(hyper));
        }), []);
  return JsxRuntime.jsx(Context.PaymentMethodsManagementSwitchContextProvider.make, {
              value: match[0],
              children: JsxRuntime.jsx(Context.PaymentMethodsManagementElementsContextProvider.make, {
                    value: match$1[0],
                    children: props.children
                  })
            });
}

var make = HyperManagementElements;

export {
  make ,
}
/* react Not a pure module */
