// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as PaymentMethodsManagementElementWrapper from "./PaymentMethodsManagementElementWrapper.bs.js";

var make = React.forwardRef(function (param, imperativeRef) {
      return JsxRuntime.jsx(PaymentMethodsManagementElementWrapper.make, {
                  id: param.id,
                  options: param.options,
                  onChange: param.onChange,
                  onReady: param.onReady,
                  componentType: param.componentType,
                  onFocus: param.onFocus,
                  onBlur: param.onBlur,
                  onClick: param.onClick,
                  imperativeRef: Caml_option.some(imperativeRef)
                });
    });

export {
  make ,
}
/* make Not a pure module */
