// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as PaymentElementsWrapper from "./PaymentElementsWrapper.bs.js";

var make = React.forwardRef(function (props, ref_) {
      return JsxRuntime.jsx(PaymentElementsWrapper.make, {
                  id: props.id,
                  options: props.options,
                  onChange: props.onChange,
                  onReady: props.onReady,
                  componentType: "payment",
                  onFocus: props.onFocus,
                  onBlur: props.onBlur,
                  onClick: props.onClick,
                  onPaymentComplete: props.onPaymentComplete,
                  onPaymentButtonClick: props.onPaymentButtonClick,
                  imperativeRef: Caml_option.some(ref_)
                });
    });

export {
  make ,
}
/* make Not a pure module */
