// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";

function PaymentMethodsManagementElement(props) {
  var onClick = props.onClick;
  var onBlur = props.onBlur;
  var onFocus = props.onFocus;
  var __componentType = props.componentType;
  var onReady = props.onReady;
  var onChange = props.onChange;
  var options = props.options;
  var __id = props.id;
  var id = __id !== undefined ? __id : "payment-management";
  var componentType = __componentType !== undefined ? __componentType : "paymentMethodsManagement";
  var hyperSwitch = React.useContext(Context.paymentMethodsManagementSwitchContext);
  var paymentMethodsManagementState = React.useContext(Context.paymentMethodsManagementElementsContext);
  var divRef = React.useRef(null);
  var paymentElement = paymentMethodsManagementState.create(componentType, options);
  React.useEffect((function () {
          var paymentElement = paymentMethodsManagementState.create(componentType, options);
          paymentElement.mount("#orca-elements-payment-management-" + id);
        }), [
        divRef,
        paymentMethodsManagementState
      ]);
  React.useEffect((function () {
          paymentElement.on("ready", onReady);
          paymentElement.on("focus", onFocus);
          paymentElement.on("blur", onBlur);
          paymentElement.on("clickTriggered", onClick);
          paymentElement.on("change", onChange);
          return (function () {
                    paymentElement.on("ready", undefined);
                    paymentElement.on("focus", undefined);
                    paymentElement.on("blur", undefined);
                    paymentElement.on("clickTriggered", undefined);
                    paymentElement.on("change", undefined);
                  });
        }), [
        paymentMethodsManagementState,
        hyperSwitch
      ]);
  return JsxRuntime.jsx("div", {
              ref: Caml_option.some(divRef),
              id: "orca-elements-payment-management-" + id
            });
}

var make = PaymentMethodsManagementElement;

export {
  make ,
}
/* react Not a pure module */
