// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as PaymentElementsWrapper from "./PaymentElementsWrapper.bs.js";

function PayPalElement(props) {
  return JsxRuntime.jsx(PaymentElementsWrapper.make, {
              id: props.id,
              options: props.options,
              onChange: props.onChange,
              onReady: props.onReady,
              componentType: "payPal",
              onFocus: props.onFocus,
              onBlur: props.onBlur,
              onClick: props.onClick,
              onPaymentComplete: props.onPaymentComplete,
              onPaymentButtonClick: props.onPaymentButtonClick
            });
}

var make = PayPalElement;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
