// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as OrcaJs from "./OrcaJs.bs.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";

function confirmPaymentFn(_elements) {
  return Promise.resolve({});
}

function confirmCardPaymentFn(_clientSecretId, _data, _options) {
  return Promise.resolve({});
}

function retrievePaymentIntentFn(_paymentIntentId) {
  return Promise.resolve({});
}

function paymentRequest(options) {
  return options;
}

function defaultGetCustomerSavedPaymentMethods(_options) {
  return Promise.resolve(null);
}

function defaultInitPaymentSession_updateIntent(param) {
  return Promise.resolve({});
}

var defaultInitPaymentSession = {
  getCustomerSavedPaymentMethods: defaultGetCustomerSavedPaymentMethods,
  updateIntent: defaultInitPaymentSession_updateIntent
};

function defaultSwitchContext_initPaymentSession(param) {
  return defaultInitPaymentSession;
}

function defaultSwitchContext_completeUpdateIntent(param) {
  return Promise.resolve({});
}

function defaultSwitchContext_initiateUpdateIntent() {
  return Promise.resolve({});
}

function defaultSwitchContext_confirmTokenization(param) {
  return Promise.resolve({});
}

var defaultSwitchContext = {
  clientSecret: "",
  confirmPayment: confirmPaymentFn,
  confirmCardPayment: confirmCardPaymentFn,
  retrievePaymentIntent: retrievePaymentIntentFn,
  paymentRequest: paymentRequest,
  initPaymentSession: defaultSwitchContext_initPaymentSession,
  completeUpdateIntent: defaultSwitchContext_completeUpdateIntent,
  initiateUpdateIntent: defaultSwitchContext_initiateUpdateIntent,
  confirmTokenization: defaultSwitchContext_confirmTokenization
};

var switchContext = React.createContext(defaultSwitchContext);

var make = switchContext.Provider;

var SwitchContextProvider = {
  make: make
};

var defaultPaymentMethodsManagementSwitchContext = {
  ephemeralKey: "",
  paymentRequest: paymentRequest
};

var paymentMethodsManagementSwitchContext = React.createContext(defaultPaymentMethodsManagementSwitchContext);

var make$1 = switchContext.Provider;

var PaymentMethodsManagementSwitchContextProvider = {
  make: make$1
};

function getString(dict, key, defaultVal) {
  return Core__Option.getOr(Belt_Option.flatMap(dict[key], Core__JSON.Decode.string), defaultVal);
}

function elementsOptionObjMapper(options) {
  var dict = Core__Option.getOr(Core__JSON.Decode.object(options), {});
  return {
          fonts: Core__Option.getOr(Belt_Option.flatMap(dict["fonts"], Core__JSON.Decode.array), []),
          locale: getString(dict, "locale", ""),
          clientSecret: getString(dict, "clientSecret", ""),
          appearance: Core__Option.getOr(Belt_Option.flatMap(dict["appearance"], Core__JSON.Decode.object), {}),
          loader: getString(dict, "loader", "auto")
        };
}

function update(_options) {
  
}

function getElement(_componentName) {
  
}

function fetchUpdates() {
  return new Promise((function (resolve, param) {
                setTimeout((function () {
                        resolve({});
                      }), 1000);
              }));
}

function create(_componentType, _options) {
  return OrcaJs.defaultPaymentElement;
}

function defaultCardForm_create(_fieldType, _options) {
  return OrcaJs.defaultFieldHandle;
}

function defaultCardForm_on(_str, _func) {
  
}

function defaultCardForm_confirmPayment() {
  return Promise.resolve(OrcaJs.sdkNotReadyError());
}

function defaultCardForm_deinit() {
  
}

function defaultCardForm_update(_x) {
  
}

var defaultCardForm_fields = {
  contents: {}
};

var defaultCardForm = {
  create: defaultCardForm_create,
  on: defaultCardForm_on,
  confirmPayment: defaultCardForm_confirmPayment,
  deinit: defaultCardForm_deinit,
  update: defaultCardForm_update,
  fields: defaultCardForm_fields
};

var defaultElementsContext_options = {
  fonts: [],
  locale: "",
  clientSecret: "",
  appearance: {},
  loader: ""
};

function defaultElementsContext_updateIntent(param) {
  return Promise.resolve({});
}

function defaultElementsContext_cardForm() {
  return defaultCardForm;
}

var defaultElementsContext = {
  options: defaultElementsContext_options,
  update: update,
  getElement: getElement,
  fetchUpdates: fetchUpdates,
  create: create,
  updateIntent: defaultElementsContext_updateIntent,
  cardForm: defaultElementsContext_cardForm,
  isReady: false
};

var elementsContext = React.createContext(defaultElementsContext);

var make$2 = elementsContext.Provider;

var ElementsContextProvider = {
  make: make$2
};

function defaultCardFormContext_createField(_fieldType, _options) {
  return OrcaJs.defaultFieldHandle;
}

function defaultCardFormContext_confirmPayment() {
  return Promise.resolve(OrcaJs.sdkNotReadyError());
}

function defaultCardFormContext_tokenize() {
  return Promise.resolve(OrcaJs.sdkNotReadyError());
}

function defaultCardFormContext_on(_str, _func) {
  
}

function defaultCardFormContext_update(_x) {
  
}

function defaultCardFormContext_deinit() {
  
}

function defaultCardFormContext_getFields() {
  return {};
}

var defaultCardFormContext = {
  createField: defaultCardFormContext_createField,
  confirmPayment: defaultCardFormContext_confirmPayment,
  tokenize: defaultCardFormContext_tokenize,
  on: defaultCardFormContext_on,
  update: defaultCardFormContext_update,
  deinit: defaultCardFormContext_deinit,
  getFields: defaultCardFormContext_getFields,
  isReady: false
};

var cardFormContext = React.createContext(defaultCardFormContext);

var make$3 = cardFormContext.Provider;

var CardFormContextProvider = {
  make: make$3
};

var defaultPaymentMethodsSessionContext = {
  session: undefined,
  isPresent: false
};

var pendingPaymentMethodsSessionContext = {
  session: undefined,
  isPresent: true
};

var paymentMethodsSessionContext = React.createContext(defaultPaymentMethodsSessionContext);

var make$4 = paymentMethodsSessionContext.Provider;

var PaymentMethodsSessionContextProvider = {
  make: make$4
};

function paymentMethodsManagementElementsOptionObjMapper(options) {
  var dict = Core__Option.getOr(Core__JSON.Decode.object(options), {});
  return {
          fonts: Core__Option.getOr(Belt_Option.flatMap(dict["fonts"], Core__JSON.Decode.array), []),
          locale: getString(dict, "locale", ""),
          ephemeralKey: getString(dict, "ephemeralKey", ""),
          appearance: Core__Option.getOr(Belt_Option.flatMap(dict["appearance"], Core__JSON.Decode.object), {}),
          loader: getString(dict, "loader", "auto")
        };
}

function defaultPaymentSessionContext_getCustomerSavedPaymentMethods(_options) {
  return Promise.resolve({});
}

function defaultPaymentSessionContext_updateIntent(param) {
  return Promise.resolve({});
}

var defaultPaymentSessionContext = {
  getCustomerSavedPaymentMethods: defaultPaymentSessionContext_getCustomerSavedPaymentMethods,
  updateIntent: defaultPaymentSessionContext_updateIntent
};

var paymentSessionContext = React.createContext(defaultPaymentSessionContext);

var make$5 = paymentSessionContext.Provider;

var PaymentSessionContextProvider = {
  make: make$5
};

var defaultPaymentMethodsManagementElementsContext_options = {
  fonts: [],
  locale: "",
  ephemeralKey: "",
  appearance: {},
  loader: ""
};

var defaultPaymentMethodsManagementElementsContext = {
  options: defaultPaymentMethodsManagementElementsContext_options,
  update: update,
  getElement: getElement,
  fetchUpdates: fetchUpdates,
  create: create
};

var paymentMethodsManagementElementsContext = React.createContext(defaultPaymentMethodsManagementElementsContext);

var make$6 = paymentMethodsManagementElementsContext.Provider;

var PaymentMethodsManagementElementsContextProvider = {
  make: make$6
};

export {
  confirmPaymentFn ,
  confirmCardPaymentFn ,
  retrievePaymentIntentFn ,
  paymentRequest ,
  defaultGetCustomerSavedPaymentMethods ,
  defaultInitPaymentSession ,
  defaultSwitchContext ,
  switchContext ,
  SwitchContextProvider ,
  defaultPaymentMethodsManagementSwitchContext ,
  paymentMethodsManagementSwitchContext ,
  PaymentMethodsManagementSwitchContextProvider ,
  getString ,
  elementsOptionObjMapper ,
  update ,
  getElement ,
  fetchUpdates ,
  create ,
  defaultCardForm ,
  defaultElementsContext ,
  elementsContext ,
  ElementsContextProvider ,
  defaultCardFormContext ,
  cardFormContext ,
  CardFormContextProvider ,
  defaultPaymentMethodsSessionContext ,
  pendingPaymentMethodsSessionContext ,
  paymentMethodsSessionContext ,
  PaymentMethodsSessionContextProvider ,
  paymentMethodsManagementElementsOptionObjMapper ,
  defaultPaymentSessionContext ,
  paymentSessionContext ,
  PaymentSessionContextProvider ,
  defaultPaymentMethodsManagementElementsContext ,
  paymentMethodsManagementElementsContext ,
  PaymentMethodsManagementElementsContextProvider ,
}
/* switchContext Not a pure module */
