// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CardCVC from "./components/CardCVC.bs.js";
import * as Context from "./Context.bs.js";
import * as Elements from "./components/Elements.bs.js";
import * as CardExpiry from "./components/CardExpiry.bs.js";
import * as CardNumber from "./components/CardNumber.bs.js";
import * as CardElement from "./components/CardElement.bs.js";
import * as PazeElement from "./components/PazeElement.bs.js";
import * as HyperElements from "./components/HyperElements.bs.js";
import * as PayPalElement from "./components/PayPalElement.bs.js";
import * as PaymentElement from "./components/PaymentElement.bs.js";
import * as ApplePayElement from "./components/ApplePayElement.bs.js";
import * as GooglePayElement from "./components/GooglePayElement.bs.js";
import * as ExpressCheckoutElement from "./components/ExpressCheckoutElement.bs.js";
import * as HyperManagementElements from "./components/HyperManagementElements.bs.js";
import * as PaymentMethodsManagementElement from "./components/PaymentMethodsManagementElement.bs.js";

function useHyper() {
  return React.useContext(Context.switchContext);
}

function useHyperManagement() {
  return React.useContext(Context.paymentMethodsManagementSwitchContext);
}

function useStripe() {
  console.warn("useStripe() is deprecated. Use useHyper() instead");
  return React.useContext(Context.switchContext);
}

function useWidgets() {
  return React.useContext(Context.elementsContext);
}

function useElements() {
  console.warn("useElements() is deprecated. Use useWidgets() instead");
  return React.useContext(Context.elementsContext);
}

var Elements$1 = Elements.make;

var HyperElements$1 = HyperElements.make;

var PaymentElement$1 = PaymentElement.make;

var UnifiedCheckout = PaymentElement.make;

var CardElement$1 = CardElement.make;

var CardWidget = CardElement.make;

var CardNumberElement = CardNumber.make;

var CardNumberWidget = CardNumber.make;

var CardCVCElement = CardCVC.make;

var CardCVCWidget = CardCVC.make;

var CardExpiryElement = CardExpiry.make;

var CardExpiryWidget = CardExpiry.make;

var GooglePayElement$1 = GooglePayElement.make;

var ApplePayElement$1 = ApplePayElement.make;

var PazeElement$1 = PazeElement.make;

var PayPalElement$1 = PayPalElement.make;

var ExpressCheckoutElement$1 = ExpressCheckoutElement.make;

var HyperManagementElements$1 = HyperManagementElements.make;

var PaymentMethodsManagementElement$1 = PaymentMethodsManagementElement.make;

export {
  useHyper ,
  useStripe ,
  useHyperManagement ,
  useWidgets ,
  useElements ,
  Elements$1 as Elements,
  HyperElements$1 as HyperElements,
  PaymentElement$1 as PaymentElement,
  UnifiedCheckout ,
  CardElement$1 as CardElement,
  CardWidget ,
  CardNumberElement ,
  CardNumberWidget ,
  CardCVCElement ,
  CardCVCWidget ,
  CardExpiryElement ,
  CardExpiryWidget ,
  GooglePayElement$1 as GooglePayElement,
  ApplePayElement$1 as ApplePayElement,
  PazeElement$1 as PazeElement,
  PayPalElement$1 as PayPalElement,
  ExpressCheckoutElement$1 as ExpressCheckoutElement,
  HyperManagementElements$1 as HyperManagementElements,
  PaymentMethodsManagementElement$1 as PaymentMethodsManagementElement,
}
/* react Not a pure module */
