// Generated by ReScript, PLEASE EDIT WITH CARE


var normalizeToPromise = (function(value) {
    if (value !== null && typeof value === 'object' && typeof value.then === 'function') {
      return value
    }
    return Promise.resolve(value)
  });

export {
  normalizeToPromise ,
}
/* No side effect */
