// Generated by ReScript, PLEASE EDIT WITH CARE


function normalizeToPromise(value) {
  var match = value["then"];
  if (match !== undefined) {
    return value;
  } else {
    return Promise.resolve(value);
  }
}

export {
  normalizeToPromise ,
}
/* No side effect */
